### ISSUE TITLE
eSigner demo missing CREDENTIAL_ID

### ISSUE THREAD

**Issue by adrelanos** [SSLcom/esigner-codesign#4]
I want to test eSigner. Can I please know the demo `CREDENTIAL_ID`?

Looking at https://www.ssl.com/guide/esigner-demo-credentials-and-certificates but not seeing it there.

* Username: `esigner_demo`
* Password: `esignerDemo#1`

But `CREDENTIAL_ID` is different.

I don't have an order number yet as i am in process of testing eSigner demo to find out if I will be able to use it.

No, it's not `CLIENT_ID=qOUeZCCzSqgA93acB3LYq6lBNjgZdiOxQc-KayC3UMw` / `qOUeZCCzSqgA93acB3LYq6lBNjgZdiOxQc-KayC3UMw`. That's something else.

> Error: Invalid credentialID parameter

It can also not be generated.

    bash ./CodeSignTool.sh get_credential_ids -username='esigner_demo' -password='esignerDemo#1'

> Error: The  provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

My idea was to test https://github.com/SSLcom/codesigner-github-sample. By adding:

* `ES_USERNAME`
* `ES_PASSWORD`
* `CREDENTIAL_ID`
* `ES_TOTP_SECRET`

to github secret environment variables, I should be able to do test signing.

If you wish to provide a public demo, then I guess the `CREDENTIAL_ID` should be public for everybody. Currently it's missing.

**Comment by bmilsom** [comment]
Hi adrelanos, 

I ran into the same problem. For me, I found the solution was to:
1. Comment out or otherwise exclude CREDENTIAL_ID from being defined.
2. Set environment_name: TEST

After doing this, I was able to successfully sign with the demo/test environment. The details for the demo environment mentions that the 'Client Secret' is not a required parameter for the demo environment, I can only assume that in the ccontext of the GitHub action, this is referring to the CREDENTIAL_ID.

Hope this helps.

**Comment by adrelanos** [comment]
I've deleted `CREDENTIAL_ID` and set `TEST=true`. That helped. Now success.

Thank you!

**Comment by bayrakmustafa** [comment]
@bmilsom @adrelanos https://github.com/SSLcom/ci-images/blob/main/.env here is the necessary information for the demo user. You can use it whenever you need. In addition, there is CodeSignTool properties file of the test environment at https://github.com/SSLcom/ci-images/blob/main/codesign-tool/conf/code_sign_tool_demo.properties.
